language: go
sudo: false
branch:
  only: master
before_install:
 - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
 - dep ensure
script:
 - go test -race -cover -covermode=atomic
 - go install && go-testcov
 - go fmt && git diff --exit-code
