language: go
sudo: false
branches:
  only: master
go:
 - "1.13"
 - "1.12"
 - "1.11"
 - "1.10"
 - "1.9"
script: cd test && go test -race -cover -covermode=atomic && cd .. && go install && cd test && go-testcov && cd .. && go vet && [ -z "`go fmt`" ]
